package DB;
// Generated 23/11/2020 19:14:42 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departamentos generated by hbm2java
 */
public class Departamentos  implements java.io.Serializable {


     private Integer idDepartamento;
     private String nome;
     private String descri;
     private Set funcionarioses = new HashSet(0);
     private Set inventarios = new HashSet(0);

    public Departamentos() {
    }

    public Departamentos(String nome, String descri, Set funcionarioses, Set inventarios) {
       this.nome = nome;
       this.descri = descri;
       this.funcionarioses = funcionarioses;
       this.inventarios = inventarios;
    }
   
    public Integer getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(Integer idDepartamento) {
        this.idDepartamento = idDepartamento;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getDescri() {
        return this.descri;
    }
    
    public void setDescri(String descri) {
        this.descri = descri;
    }
    public Set getFuncionarioses() {
        return this.funcionarioses;
    }
    
    public void setFuncionarioses(Set funcionarioses) {
        this.funcionarioses = funcionarioses;
    }
    public Set getInventarios() {
        return this.inventarios;
    }
    
    public void setInventarios(Set inventarios) {
        this.inventarios = inventarios;
    }




}


