package DB;
// Generated 23/11/2020 19:14:42 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Equipamentos generated by hbm2java
 */
public class Equipamentos  implements java.io.Serializable {


     private String chaveEquip;
     private String nome;
     private Set inventarios = new HashSet(0);

    public Equipamentos() {
    }

	
    public Equipamentos(String chaveEquip) {
        this.chaveEquip = chaveEquip;
    }
    public Equipamentos(String chaveEquip, String nome, Set inventarios) {
       this.chaveEquip = chaveEquip;
       this.nome = nome;
       this.inventarios = inventarios;
    }
   
    public String getChaveEquip() {
        return this.chaveEquip;
    }
    
    public void setChaveEquip(String chaveEquip) {
        this.chaveEquip = chaveEquip;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getInventarios() {
        return this.inventarios;
    }
    
    public void setInventarios(Set inventarios) {
        this.inventarios = inventarios;
    }




}


