package DB;
// Generated 23/11/2020 19:14:42 by Hibernate Tools 4.3.1



/**
 * Inventario generated by hbm2java
 */
public class Inventario  implements java.io.Serializable {


     private Integer idInv;
     private Departamentos departamentos;
     private Equipamentos equipamentos;

    public Inventario() {
    }

    public Inventario(Departamentos departamentos, Equipamentos equipamentos) {
       this.departamentos = departamentos;
       this.equipamentos = equipamentos;
    }
   
    public Integer getIdInv() {
        return this.idInv;
    }
    
    public void setIdInv(Integer idInv) {
        this.idInv = idInv;
    }
    public Departamentos getDepartamentos() {
        return this.departamentos;
    }
    
    public void setDepartamentos(Departamentos departamentos) {
        this.departamentos = departamentos;
    }
    public Equipamentos getEquipamentos() {
        return this.equipamentos;
    }
    
    public void setEquipamentos(Equipamentos equipamentos) {
        this.equipamentos = equipamentos;
    }




}


